# Enhanced Dependabot Configuration for GLPI Dashboard
# Automatically creates PRs to update dependencies with security focus
# Includes vulnerability alerts and automated security updates

version: 2
updates:
  # Python dependencies (backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jonathan-moletta"
    assignees:
      - "jonathan-moletta"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "python"
      - "security"
    allow:
      - dependency-type: "all"
    # Group minor and patch updates
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-security:
        patterns:
          - "*"
        dependency-type: "security"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Enable vulnerability alerts
    vulnerability-alerts:
      enabled: true

  # Python dependencies (root)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "jonathan-moletta"
    assignees:
      - "jonathan-moletta"
    commit-message:
      prefix: "deps(root)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "security"
    allow:
      - dependency-type: "all"
    groups:
      root-python-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    vulnerability-alerts:
      enabled: true

  # NPM dependencies (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jonathan-moletta"
    assignees:
      - "jonathan-moletta"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
      - "security"
    allow:
      - dependency-type: "all"
    # Group updates for better management
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "eslint*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        dependency-type: "security"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    vulnerability-alerts:
      enabled: true

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "jonathan-moletta"
    assignees:
      - "jonathan-moletta"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
      - "security"
    allow:
      - dependency-type: "all"
    groups:
      github-actions-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    vulnerability-alerts:
      enabled: true

  # Docker (if using Docker in the future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "jonathan-moletta"
    assignees:
      - "jonathan-moletta"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    allow:
      - dependency-type: "all"
    groups:
      docker-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    vulnerability-alerts:
      enabled: true