global:
  smtp_smarthost: ''localhost:587''
  smtp_from: ''alertmanager@glpi-dashboard.local''
  smtp_auth_username: ''alertmanager@glpi-dashboard.local''
  smtp_auth_password: ''password''

route:
  group_by: [''alertname'']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: ''web.hook''
  routes:
  - match:
      severity: critical
    receiver: ''critical-alerts''
  - match:
      severity: warning
    receiver: ''warning-alerts''

receivers:
- name: ''web.hook''
  webhook_configs:
  - url: ''http://localhost:5001/alerts''
    send_resolved: true

- name: ''critical-alerts''
  email_configs:
  - to: ''admin@glpi-dashboard.local''
    subject: ''[CRÍTICO] GLPI Dashboard Alert''
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ .CommonAnnotations.summary }}
      Description: {{ .CommonAnnotations.description }}
      
      Details:
      {{ range .Alerts }}
      - Alert: {{ .Annotations.title }}
        Status: {{ .Status }}
        Labels: {{ .Labels }}
      {{ end }}
  slack_configs:
  - api_url: ''https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK''
    channel: ''#alerts''
    title: ''GLPI Dashboard - Alerta Crítico''
    text: ''{{ .CommonAnnotations.summary }}''

- name: ''warning-alerts''
  email_configs:
  - to: ''team@glpi-dashboard.local''
    subject: ''[WARNING] GLPI Dashboard Alert''
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ .CommonAnnotations.summary }}
      Description: {{ .CommonAnnotations.description }}

inhibit_rules:
  - source_match:
      severity: ''critical''
    target_match:
      severity: ''warning''
    equal: [''alertname'', ''dev'', ''instance'']
